replicaCount: 1

image:
  repository: 192.168.1.53:5000/c-server
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
